### create user
POST http://localhost:7787/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZBdF9GajRYdUhJUjN2c3k2QlV6aSJ9.eyJpc3MiOiJodHRwczovL3l1bW15cmVzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJkVVNabDNkMG1FbXlyWEpZMXNUbWFaQjNPS1dyUTkyR0BjbGllbnRzIiwiYXVkIjoiaHR0cDovL2FwaS15dW1teXJlc3RybyIsImlhdCI6MTY4MTE4MDUxMiwiZXhwIjoxNjgxMjY2OTEyLCJhenAiOiJkVVNabDNkMG1FbXlyWEpZMXNUbWFaQjNPS1dyUTkyRyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.kwUL5j6u3TgwzbsC41sEa4rcgBEsd3u8zuca9WmkFyoThZ-1A8ASkQLaLxzywvXOAoLvWX85yZLkHijhBNgxjes1sr9QRN2Ar2Ain9H71loA1Eo8ScivKw2uWU0LtigHQy_XZYCe-SgZlSUCTJ5yjKxPyUPilxPgI_xCRhLmxLgFWlqEMhxS7YsWSl1-qiY5snk1uh4Nze2wb0cTYlIj11Z7CZbE_9J8o-QCp-i3JgivsmppZDl6TAEdVs_chRaHOxrdIhxX_zCVgeoBhpS94ofE9pTfsL2JEihrEmLdMVztSxz5K16sRzSSOmOiGd9WdbqOTeXgDwxI8WfHz4ZA1A

{
    "_id":"Test 105",
    "email":"shiva@ssss.com"
}

