### get all catagories
GET https://backend-yummy-restro.herokuapp.com/api/categories
Accept: application/json

### create a new catagory
POST https://backend-yummy-restro.herokuapp.com/api/categories
Content-Type: application/json
Accept: application/json

{
    "name":"Panipuri"
}

### Get catagory by id
GET http://localhost:7787/api/categories/63fb982a21e40ed7b2e71441
Accept: application/json

